// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB33zsPfTRgD9X3jVP7HB7oRTiebFtlZoM',
    appId: '1:525247338366:web:c9d10580e2e98bc3e1c52f',
    messagingSenderId: '525247338366',
    projectId: 'questions-1ff2f',
    authDomain: 'questions-1ff2f.firebaseapp.com',
    storageBucket: 'questions-1ff2f.appspot.com',
    measurementId: 'G-Y8DB1JXFLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVwHnZHoU5v3szC4sEITS1Ydiqoa_L1YE',
    appId: '1:525247338366:android:85f880e975abc018e1c52f',
    messagingSenderId: '525247338366',
    projectId: 'questions-1ff2f',
    storageBucket: 'questions-1ff2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8jsl6fMilEyRNtJqciSe17JlPOm7d9Y',
    appId: '1:525247338366:ios:54e745278aa6acfbe1c52f',
    messagingSenderId: '525247338366',
    projectId: 'questions-1ff2f',
    storageBucket: 'questions-1ff2f.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8jsl6fMilEyRNtJqciSe17JlPOm7d9Y',
    appId: '1:525247338366:ios:ceef1f4a75774516e1c52f',
    messagingSenderId: '525247338366',
    projectId: 'questions-1ff2f',
    storageBucket: 'questions-1ff2f.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
